name: Go

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Vet
        run: go vet ./...

  lint:
    runs-on: ubuntu-latest
    steps:

      # The `install` flag sets up docker build command as an alias to docker buildx
      # see: https://github.com/docker/setup-buildx-action#inputs
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - uses: actions/checkout@v3

      - name: Lint Go code with golang-ci
        uses: golangci/golangci-lint-action@v3
        with:
          args: --verbose --sort-results --max-issues-per-linter 0 --max-same-issues 0 --timeout 5m0s --skip-dirs='(tests|third_party)'
          only-new-issues: true
          skip-pkg-cache: true
          skip-build-cache: true
          version: latest
